name: Node.js Test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '37 22 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Yarn
        run: npm install -g yarn
      - name: Install
        run: yarn install
      - name: Test
        env:
          TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
          TWITTER_PASSWORD: ${{ secrets.TWITTER_PASSWORD }}
          TWITTER_EMAIL: ${{ secrets.TWITTER_EMAIL }}
        run: yarn test
